### ISSUE TITLE
Can't use ctrl+click to open a link while editing a textbox in Firefox

### ISSUE THREAD

**Issue by nitzanms** [microsoft/roosterjs-react#103]
[I opened an issue in Azure DevOps and they directed me to you as owners of the editor](https://developercommunity.visualstudio.com/content/problem/719282/cant-use-ctrlclick-to-open-a-link-while-editing-a.html).

Repro steps:
1. Using Firefox, create a new work item with a link in its Description textbox.
2. Ctrl+click the link. A new windows with the link will NOT open. (Bug)
3. Exit the textbox by clicking outside it.
4. Click the link. A new window will open with the link. (Desired behavior)

**Comment by JiuqingSong** [comment]
This repo is archived now. For react wrapper of roosterjs, please refer to [roosterjs-react](https://github.com/microsoft/roosterjs/tree/master/packages-ui) package in [roosterjs](https://github.com/microsoft/roosterjs) repo. Thanks.
