### ISSUE TITLE
Readme is Missing ... Everything Except a Contribution Note

### ISSUE THREAD

**Issue by machineghost** [microsoft/roosterjs-react#121]
https://github.com/microsoft/roosterjs-react doesn't have even the most basic description of the library or a single usage example, let alone documentation or a link to a documentation site.  This makes it rather difficult for anyone to actually learn/use the library.

**Comment by JiuqingSong** [comment]
This repo is archived now. For react wrapper of roosterjs, please refer to [roosterjs-react](https://github.com/microsoft/roosterjs/tree/master/packages-ui) package in [roosterjs](https://github.com/microsoft/roosterjs) repo. Thanks.
