### ISSUE TITLE
Accessibility issue in RoosterCommandBar

### ISSUE THREAD

**Issue by micarls** [microsoft/roosterjs-react#125]
![image](https://user-images.githubusercontent.com/41308449/138755868-b98e17c8-4d2a-44b5-b86a-2303fe59a5d1.png)
The screen reader should read as bold 1 of 8, italic 2 of 8, etc.

**Comment by jvillalobos** [comment]
This should be fixed now on https://github.com/microsoft/roosterjs/issues/846. Please reopen in the main repo if you can still reproduce.
