### ISSUE TITLE
Accessibility issue in LeanRooster.tsx

### ISSUE THREAD

**Issue by Dragomir2020** [microsoft/roosterjs-react#137]
When in view only mode the LeanRooster component should not be focusable and when using narrator should not say the word "Edit"

Two things
* Remove role="textbox" when in edit mode
* Remove tabIndex when in edit mode

**Comment by JiuqingSong** [comment]
This repo is archived now. For react wrapper of roosterjs, please refer to [roosterjs-react](https://github.com/microsoft/roosterjs/tree/master/packages-ui) package in [roosterjs](https://github.com/microsoft/roosterjs) repo. Thanks.
