### ISSUE TITLE
ContentChangedPLugin: Onchange event not working with setState

### ISSUE THREAD

**Issue by krishnakprakash** [microsoft/roosterjs-react#83]
I have added contentChangedPlugin to get the onChange value of editor and it works fine if i console the value. 

But when i try to update my components state within onChange event using setState it stops working.

Is there any documentation available got implementing onChange or do you guys have any example to refer.

**Comment by eimerreis** [comment]
I'm also facing this issue, which makes using the rooster Editor really uncomfortable. 

I tried working around this problem by passing an `editorViewState` object as a property without success. From the moment you call `setState` in the parent component, the CommandBar Buttons are not working anymore in my setup. 

@JiuqingSong can you help out here?

**Comment by ms-leemina** [comment]
Hi, I'm wondering if this issue has resolved. I'm also in the same situation that onChange is not working.

**Comment by JiuqingSong** [comment]
This repo is used as a demo of how to use roosterjs with react. It is not actively maintained, and may be closed any time. We recommend not using the code here in your product. Instead, please use roosterjs directly and build your own wrapper.

Thanks.

**Comment by JiuqingSong** [comment]
This repo is archived now. For react wrapper of roosterjs, please refer to [roosterjs-react](https://github.com/microsoft/roosterjs/tree/master/packages-ui) package in [roosterjs](https://github.com/microsoft/roosterjs) repo. Thanks.
