### ISSUE TITLE
Unexpected toolbar behavior when browser loses focus

### ISSUE THREAD

**Issue by racbatch** [microsoft/roosterjs-react#87]
The toolbar is hidden whenever it loses focus, but is only deactivated when the roosterjs editor becomes an inactive element.  If these events don't happen at the same time (such as if you move focus outside of the browser by using/opening another window), then you'll be able to activate a toolbar button by "clicking" on its location, even though the button isn't visible.

This is more of an edge case issue, but it can lead to some confusing behavior (i.e. accidentally indenting your text when you're trying to click back into the editor).

**Comment by JiuqingSong** [comment]
This repo is archived now. For react wrapper of roosterjs, please refer to [roosterjs-react](https://github.com/microsoft/roosterjs/tree/master/packages-ui) package in [roosterjs](https://github.com/microsoft/roosterjs) repo. Thanks.
