### ISSUE TITLE
Select text and add hyperlink not workin

### ISSUE THREAD

**Issue by rabwill** [microsoft/roosterjs-react#92]
While selecting a text and adding a hyperlink, the text is lost and the hyperlink is added as raw hyperlink. Using this component in a SPFx solution. 
SPFx version 1.8.2

**Comment by Arkmelky** [comment]
I will pick it.

**Comment by JiuqingSong** [comment]
This repo is archived now. For react wrapper of roosterjs, please refer to [roosterjs-react](https://github.com/microsoft/roosterjs/tree/master/packages-ui) package in [roosterjs](https://github.com/microsoft/roosterjs) repo. Thanks.
