### ISSUE TITLE
When clicking insert hyperlink the popup input text is not focused

### ISSUE THREAD

**Issue by engineersamuel** [microsoft/roosterjs-react#94]
Repro Steps:

* C&P'ing from https://github.com/microsoft/roosterjs-react/blob/master/sample/script/ReactEditor.tsx
* Click the Ribbon "Insert Hyperlink"
* The popup that has the URL: does not auto-focus. And at least in my page I can't click it, I have to tab once to focus it, then I can input text.
* Also the close button is not working by default

Env:
* "roosterjs-react": "0.0.71",
* "roosterjs-react-ribbon": "0.0.71",
* The ReactEditor.tsx is being opened from an Office Fabric React Panel.

**Comment by JiuqingSong** [comment]
This repo is archived now. For react wrapper of roosterjs, please refer to [roosterjs-react](https://github.com/microsoft/roosterjs/tree/master/packages-ui) package in [roosterjs](https://github.com/microsoft/roosterjs) repo. Thanks.
