### ISSUE TITLE
Default behavior of inserting a hyperlink inserts it to the front of text

### ISSUE THREAD

**Issue by engineersamuel** [microsoft/roosterjs-react#95]
Repro Steps:

* C&P'ing from https://github.com/microsoft/roosterjs-react/blob/master/sample/script/ReactEditor.tsx
* Click the Ribbon "Insert Hyperlink"
* Type or C&P the url
* Click ok
* The hyperlink is inserted to the front of the entire text block, not to where the previous cursor position was.
* Note that I verified the component is remembering the cursor position in general, even after clicking insert hyperlink then cancelling, the prior cursor position is remembered.  

Env:
* "roosterjs-react": "0.0.71",
* "roosterjs-react-ribbon": "0.0.71",
* The ReactEditor.tsx is being opened from an Office Fabric React Panel.

**Comment by JiuqingSong** [comment]
This repo is archived now. For react wrapper of roosterjs, please refer to [roosterjs-react](https://github.com/microsoft/roosterjs/tree/master/packages-ui) package in [roosterjs](https://github.com/microsoft/roosterjs) repo. Thanks.
